---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  targetNamespace: prod
  values:
    namespaceOverride: prod
    configuration: |-
      systemLog:
        component:
          network:
            verbosity: "W"
