---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  targetNamespace: prod
  values:
    namespaceOverride: prod
  valuesFrom:
    - kind: Secret
      name: mongodb-prod
      targetPath: auth.rootPassword
      valuesKey: ROOT_PASSWORD
    - kind: Secret
      name: mongodb-prod
      targetPath: auth.replicaSetKey
      valuesKey: REPLICASET_KEY
