---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  targetNamespace: staging
  values:
    namespaceOverride: staging
    disableSystemLog: true
    persistence:
      resourcePolicy: keep
      size: 10Gi
