---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-staging-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  gcePersistentDisk:
    pdName: mongodb-staging-primary
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-staging-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: mongodb-staging-pv