---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 10s
  path: ./infrastructure/prod/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
