---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aquasecurity
  namespace: flux-system
spec:
  type: "oci"
  interval: 120m
  url: oci://ghcr.io/aquasecurity/helm-charts
