---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: trivy
  chart:
    spec:
      version: 0.x
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    serviceMonitor:
      enabled: true
      interval: 60s
    trivy:
      ignoreUnfixed: true
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
    operator:
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      configAuditScannerScanOnlyCurrentRevisions: true
      scanJobTTL: "3600"
