---
# Apply CRDs directly (cluster-scoped)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloaks.k8s.keycloak.org
spec:
  group: k8s.keycloak.org
  names:
    kind: Keycloak
    listKind: KeycloakList
    plural: keycloaks
    singular: keycloak
  scope: Namespaced
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instances:
                  type: integer
                  minimum: 1
                  maximum: 10
                hostname:
                  type: object
                  properties:
                    hostname:
                      type: string
                    admin:
                      type: string
                http:
                  type: object
                  properties:
                    httpEnabled:
                      type: boolean
                    httpsPort:
                      type: integer
                    tlsSecret:
                      type: string
                ingress:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    className:
                      type: string
                    annotations:
                      type: object
                resources:
                  type: object
                livenessProbe:
                  type: object
                readinessProbe:
                  type: object
                features:
                  type: object
                  properties:
                    enabled:
                      type: array
                      items:
                        type: string
                additionalOptions:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      secret:
                        type: object
                        properties:
                          name:
                            type: string
                          key:
                            type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                instances:
                  type: integer
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Instances
          type: integer
          jsonPath: .status.instances
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

---
# Apply CRDs directly (cluster-scoped)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakrealmimports.k8s.keycloak.org
spec:
  group: k8s.keycloak.org
  names:
    kind: KeycloakRealmImport
    listKind: KeycloakRealmImportList
    plural: keycloakrealmimports
    singular: keycloakrealmimport
  scope: Namespaced
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                keycloakCRName:
                  type: string
                realm:
                  type: object
            status:
              type: object
              properties:
                phase:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

---
# RBAC - ClusterRole for Keycloak Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-operator
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      - "services"
      - "endpoints"
      - "persistentvolumeclaims"
      - "events"
      - "configmaps"
      - "secrets"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["k8s.keycloak.org"]
    resources: ["keycloaks", "keycloakrealmimports"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["k8s.keycloak.org"]
    resources: ["keycloaks/status", "keycloakrealmimports/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
