---
# Base Keycloak operator deployment template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
  # namespace will be set by environment patches
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-operator
  template:
    metadata:
      labels:
        app: keycloak-operator
      annotations:
        apparmor.security.beta.kubernetes.io/pod: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      serviceAccountName: keycloak-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: operator
          image: quay.io/keycloak/keycloak-operator:26.3.3
          imagePullPolicy: Always
          env: []
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}

---
# NetworkPolicy for Keycloak Operator
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak-operator-network-policy
  # namespace will be set by environment patches
spec:
  podSelector:
    matchLabels:
      app: keycloak-operator
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow health check probes from kubelet
    - ports:
        - protocol: TCP
          port: 8080
      from:
        - namespaceSelector:
            matchLabels:
              name: kube-system
  egress:
    # Allow DNS resolution
    - ports:
        - protocol: UDP
          port: 53
      to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
    # Allow HTTPS to external registries and APIs
    - ports:
        - protocol: TCP
          port: 443
      to: []
    # Allow HTTP for external APIs if needed
    - ports:
        - protocol: TCP
          port: 80
      to: []
    # Allow communication with Kubernetes API server
    - ports:
        - protocol: TCP
          port: 443
      to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
    # Allow communication within the same namespace (for operator to manage Keycloak resources)
    - ports:
        - protocol: TCP
          port: 8443 # Keycloak HTTPS port
        - protocol: TCP
          port: 8080 # Keycloak HTTP port (if enabled)
      to:
        - namespaceSelector:
            matchLabels:
              name: "" # Same namespace
