---
apiVersion: keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 3
  http:
    httpEnabled: false
    httpsPort: 8443
    tlsSecret: keycloak-internal-tls
  # hostname will be set by environment-specific patches
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      nginx.ingress.kubernetes.io/server-snippet: |
        location /metrics {
          deny all;
          return 404;
        }
        location /admin {
          deny all;
          return 404;
        }
        location /realms/master/protocol/openid-connect/userinfo {
          deny all;
          return 404;
        }
    className: nginx
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 30
  readinessProbe:
    failureThreshold: 3
    periodSeconds: 10
  features:
    enabled:
      - admin-fine-grained-authz
      - ciba
      #- client-secret-rotation
      - declarative-user-profile
      #- docker
      - dynamic-scopes
      - openid-connect
      #- preview
      - recovery-codes
      - scripts
      - token-exchange
      - web-authn
  additionalOptions:
    - name: KC_CACHE
      value: "ispn"
    - name: KC_CACHE_CONFIG_FILE
      value: "cache-ispn.xml"
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KC_METRICS_ENABLED
      value: "true"
    - name: KC_LOG_LEVEL
      value: "INFO"
