---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/nginx
  - configmap-error-pages.yaml
  - frontend-config.yaml
  - ingress.yaml
patchesStrategicMerge:
  - helm-release.yaml
