---
# Cert-manager issuers kustomization with dependency
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  interval: 5m0s
  retryInterval: 1m0s
  path: ./infrastructure/dev/cert-manager-issuers-only.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure
