# Deploy Keycloak operator in demo environment
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-operator-demo
  namespace: flux-system
spec:
  interval: 5m0s
  retryInterval: 1m0s
  path: ./infrastructure/dev/keycloak-operator/keycloak-operator-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
