---
# Deploy Keycloak operators in dev environment
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-operator
  namespace: flux-system
spec:
  interval: 5m0s
  retryInterval: 1m0s
  path: ./infrastructure/dev/keycloak-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
