---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - elasticsearch.yaml
  - nginx-harvester.yaml
  - nginx-catalog.yaml
  - nginx-resource-identificators.yaml
  - keycloak.yaml