---
apiVersion: v1
kind: Service
metadata:
  name: nginx-apis
spec:
  selector:
    app: nginx-apis
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
