---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/keycloak-operator
  - rbac-prod.yaml
patches:
  - path: operator-prod-patch.yaml
    target:
      kind: Deployment
      name: keycloak-operator
  - path: network-policy-prod-patch.yaml
    target:
      kind: NetworkPolicy
      name: keycloak-operator-network-policy
