---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: flux-system
spec:
  values:
    query:
      ingress:
        # enabled: true
        hostname: thanos-query.staging.fellesdatakatalog.digdir.no
    queryFrontend:
      ingress:
        hostname: thanos.staging.fellesdatakatalog.digdir.no
    storegateway:
      ingress:
        hostname: thanos-store.staging.fellesdatakatalog.digdir.no
    compactor:
      ingress:
        # enabled: true
        hostname: thanos-compactor.staging.fellesdatakatalog.digdir.no
