---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  values:
    grafana:
      ingress:
        hosts:
          - grafana.staging.fellesdatakatalog.digdir.no
    prometheus:
      ingress:
        hosts:
          - prometheus.staging.fellesdatakatalog.digdir.no
