#!/usr/bin/env bash
# =============================================================================
# generate-imports.sh  (read-only)
#
# Introspects the LIVE digdir-fdk-prod project and emits a complete, self-
# contained import runner whose Terraform addresses match the CURRENT prod
# config (terraform/prod/*.tf). It writes NOTHING to Terraform state.
#
# Usage:
#   ./generate-imports.sh > import-resources.sh.new   # review the output
#   # then, after reviewing:  mv import-resources.sh.new import-resources.sh
#
# Coverage (all 16 resource types present in terraform/prod):
#   google_project_service, google_service_account, google_project_iam_member,
#   google_service_account_iam_member, google_iam_workload_identity_pool(+_provider),
#   google_compute_global_address, google_storage_bucket, google_sql_database_instance,
#   google_compute_disk, google_compute_security_policy, google_compute_resource_policy,
#   google_container_cluster, google_container_node_pool,
#   kubernetes_namespace, kubernetes_service_account
#
# NOTE: this script reads gcloud + the local *.tf files only. It never reads
# the secret tfvars and never prints secret values.
# =============================================================================
set -uo pipefail

PROJECT_ID="digdir-fdk-prod"
REGION="europe-north1"
ZONE="europe-north1-a"
TF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# All gcloud calls target prod explicitly (do not rely on active config).
gc() { gcloud "$@" --project="$PROJECT_ID"; }

note() { echo "# $*"; }

# -----------------------------------------------------------------------------
# Emit the runner preamble (safe_import wrapper + init reminder)
# -----------------------------------------------------------------------------
cat <<'HEADER'
#!/usr/bin/env bash
# AUTO-GENERATED by generate-imports.sh against live digdir-fdk-prod.
# Review carefully before running. Run from terraform/prod after:
#   terraform init -backend-config="bucket=digdir-fdk-prod-terraform-state"
#   (terraform.tfvars.secret-manager present)
set -uo pipefail

PROJECT_ID="digdir-fdk-prod"
REGION="europe-north1"
ZONE="europe-north1-a"

# Idempotent import: skip if already in state; never abort the whole run.
safe_import() {
  local addr="$1" id="$2"
  if terraform state show "$addr" >/dev/null 2>&1; then
    echo "  ⏭️  already in state: $addr"
  else
    echo "  ⬇️  importing: $addr"
    terraform import -var-file=terraform.tfvars.secret-manager "$addr" "$id" \
      || echo "  ⚠️  FAILED: $addr"
  fi
}

echo "=== Terraform import: production ==="
HEADER
echo

# -----------------------------------------------------------------------------
# 1. Project services (config literals — robust, no live query needed)
# -----------------------------------------------------------------------------
echo 'echo "--- google_project_service ---"'
note "Parsed from api-services.tf (address + service string are literals)."
paste -d' ' \
  <(grep -oE 'resource "google_project_service" "[^"]+"' "$TF_DIR/api-services.tf" | sed -E 's/.*"([^"]+)"$/\1/') \
  <(grep -oE 'service += +"[^"]+"' "$TF_DIR/api-services.tf" | sed -E 's/.*"([^"]+)"$/\1/') \
| while read -r addr svc; do
    [ -n "$addr" ] && echo "safe_import 'google_project_service.${addr}' '${PROJECT_ID}/${svc}'"
  done
echo

# -----------------------------------------------------------------------------
# 2. Service accounts (map live email -> config address by display_name)
#    Also capture terraform_sa / k8s_deploy_sa emails for later IAM bindings.
# -----------------------------------------------------------------------------
echo 'echo "--- google_service_account ---"'
# Match by EMAIL LOCAL-PART (stable); display names were changed out-of-band.
# Config declares 10 SAs but only 7 exist live; terraform_sa / k8s_deploy_sa /
# cf_invoker_sa are NOT provisioned in prod (create-on-apply).
TF_SA_EMAIL=""; K8S_DEPLOY_SA_EMAIL=""
while IFS= read -r email; do
  [ -z "$email" ] && continue
  case "$email" in
    *@appspot.gserviceaccount.com|*-compute@developer.gserviceaccount.com|firebase-adminsdk*|telegraf-operator@*) continue ;;
  esac
  lp="${email%%@*}"
  case "$lp" in
    *-autodeploy)     addr="autodeploy_sa" ;;
    *-bucket-sa)      addr="bucket_sa" ;;
    *-cloudsql)       addr="cloudsql_sa" ;;
    *-error-sa)       addr="error_sa" ;;
    *-eso-reader-sa)  addr="eso_reader_sa" ;;
    *-kubernetes-sa)  addr="kubernetes" ;;
    *-vertex-sa)      addr="vertex_sa" ;;
    *-cf-invoker)     addr="cf_invoker_sa" ;;
    *-terraform|terraform-sa) addr="terraform_sa"; TF_SA_EMAIL="$email" ;;
    *k8s-deploy*)     addr="k8s_deploy_sa"; K8S_DEPLOY_SA_EMAIL="$email" ;;
    *) echo "# UNMAPPED service account (review): $email"; continue ;;
  esac
  echo "safe_import 'google_service_account.${addr}' 'projects/${PROJECT_ID}/serviceAccounts/${email}'"
done < <(gc iam service-accounts list --format='value(email)' 2>/dev/null)
echo "# NOT live (create-on-apply, do not import): terraform_sa, k8s_deploy_sa, cf_invoker_sa (whichever are absent above)"
echo

# -----------------------------------------------------------------------------
# 3. Project IAM members (roles literal in config; members resolved above)
# -----------------------------------------------------------------------------
echo 'echo "--- google_project_iam_member ---"'
if [ -n "$TF_SA_EMAIL" ]; then
  for pair in \
    "terraform_sa_editor roles/editor" \
    "terraform_sa_secret_accessor roles/secretmanager.secretAccessor" \
    "terraform_sa_storage_admin roles/storage.objectAdmin" \
    "terraform_sa_workload_identity_admin roles/iam.workloadIdentityPoolAdmin" \
    "terraform_sa_project_iam_admin roles/resourcemanager.projectIamAdmin" \
    "terraform_sa_gke_admin roles/container.clusterAdmin"; do
    set -- $pair
    echo "safe_import 'google_project_iam_member.$1' '${PROJECT_ID} $2 serviceAccount:${TF_SA_EMAIL}'"
  done
else
  echo "# WARN: terraform_sa email not found live — cannot emit terraform_sa IAM bindings"
fi
if [ -n "$K8S_DEPLOY_SA_EMAIL" ]; then
  echo "safe_import 'google_project_iam_member.k8s_deploy_sa_gke_developer' '${PROJECT_ID} roles/container.developer serviceAccount:${K8S_DEPLOY_SA_EMAIL}'"
else
  echo "# WARN: k8s_deploy_sa email not found live — cannot emit k8s_deploy_sa IAM binding"
fi
echo

# -----------------------------------------------------------------------------
# 4. Service-account IAM members (WIF impersonation; members read live)
# -----------------------------------------------------------------------------
echo 'echo "--- google_service_account_iam_member (WIF) ---"'
if [ -n "$TF_SA_EMAIL" ]; then
  gc iam service-accounts get-iam-policy "$TF_SA_EMAIL" \
     --flatten='bindings[].members' \
     --filter='bindings.role=roles/iam.workloadIdentityUser' \
     --format='value(bindings.members)' 2>/dev/null \
  | while read -r m; do
      [ -z "$m" ] && continue
      echo "safe_import 'google_service_account_iam_member.github_actions_terraform_sa' 'projects/${PROJECT_ID}/serviceAccounts/${TF_SA_EMAIL} roles/iam.workloadIdentityUser ${m}'"
    done
fi
if [ -n "$K8S_DEPLOY_SA_EMAIL" ]; then
  gc iam service-accounts get-iam-policy "$K8S_DEPLOY_SA_EMAIL" \
     --flatten='bindings[].members' \
     --filter='bindings.role=roles/iam.workloadIdentityUser' \
     --format='value(bindings.members)' 2>/dev/null \
  | while read -r m; do
      [ -z "$m" ] && continue
      # for_each key is the repo (text after attribute.repository/)
      repo="${m##*/attribute.repository/}"
      echo "safe_import 'google_service_account_iam_member.github_actions_k8s_deploy_sa[\"${repo}\"]' 'projects/${PROJECT_ID}/serviceAccounts/${K8S_DEPLOY_SA_EMAIL} roles/iam.workloadIdentityUser ${m}'"
    done
fi
echo

# -----------------------------------------------------------------------------
# 5. Workload Identity Federation pool + provider (deterministic ids)
# -----------------------------------------------------------------------------
echo 'echo "--- workload identity federation ---"'
echo "safe_import 'google_iam_workload_identity_pool.github_actions' 'projects/${PROJECT_ID}/locations/global/workloadIdentityPools/github-actions'"
echo "safe_import 'google_iam_workload_identity_pool_provider.github' 'projects/${PROJECT_ID}/locations/global/workloadIdentityPools/github-actions/providers/github'"
echo

# -----------------------------------------------------------------------------
# 6. Global addresses (for_each: prod-v4 / prod-v6)
# -----------------------------------------------------------------------------
echo 'echo "--- google_compute_global_address ---"'
for key in prod-v4 prod-v6; do
  echo "safe_import 'google_compute_global_address.addresses[\"${key}\"]' 'projects/${PROJECT_ID}/global/addresses/${PROJECT_ID}-${key}'"
done
echo

# -----------------------------------------------------------------------------
# 7. Storage buckets (map live bucket -> config address by name pattern)
# -----------------------------------------------------------------------------
echo 'echo "--- google_storage_bucket ---"'
gcloud storage buckets list --project="$PROJECT_ID" --format='value(name)' 2>/dev/null \
| while read -r b; do
    [ -z "$b" ] && continue
    case "$b" in
      gcf-v2-artifacts-*)              addr="gcf_v2_artifacts" ;;
      gcf-v2-sources-*)                addr="gcf_v2_sources" ;;
      gcf-v2-uploads-*)                addr="gcf_v2_uploads" ;;
      *thanos*)                        addr="thanos_long_term_metrics" ;;
      *terraform-state*|fdk-archive)   addr="__skip__" ;;
      *) addr="" ;;
    esac
    if [ "$addr" = "__skip__" ]; then
      echo "# skip bucket '$b' (not Terraform-managed: state backend / archive)"
    elif [ -z "$addr" ]; then
      echo "# UNMAPPED bucket (review): $b"
    else
      echo "safe_import 'google_storage_bucket.${addr}' '${b}'"
    fi
  done
echo

# -----------------------------------------------------------------------------
# 8. Cloud SQL instance
# -----------------------------------------------------------------------------
echo 'echo "--- google_sql_database_instance ---"'
gc sql instances list --format='value(name)' 2>/dev/null \
| while read -r inst; do
    [ -z "$inst" ] && continue
    echo "safe_import 'google_sql_database_instance.main' '${PROJECT_ID}/${inst}'"
  done
note "PREP: before importing, mirror dev SQL config (parameterize edition/"
note "data_cache/transaction_log + retune flags) so the post-import plan is clean."
echo

# -----------------------------------------------------------------------------
# 9. Compute disks (map live disk -> config address by name suffix)
# -----------------------------------------------------------------------------
echo 'echo "--- google_compute_disk ---"'
gc compute disks list --zones="$ZONE" --format='value(name)' 2>/dev/null \
| while read -r d; do
    [ -z "$d" ] && continue
    case "$d" in
      *-prod-cms-service)        addr="prod_cms_service" ;;
      *-prod-community-service)  addr="prod_community_service" ;;
      *-prod-kafka-1)            addr="prod_kafka_1" ;;
      *-prod-kafka-2)            addr="prod_kafka_2" ;;
      *-prod-kafka-3)            addr="prod_kafka_3" ;;
      *-prod-rabbitmq)           addr="prod_rabbitmq" ;;
      *-prod-reports-store)      addr="prod_reports_store" ;;
      *-prod-sparql)             addr="prod_sparql" ;;
      *-prod-static-rdf-server)  addr="prod_static_rdf_server" ;;
      *-prod-zookeeper-1)        addr="prod_zookeeper_1" ;;
      mongodb-primary)           addr="prod_mongodb_primary" ;;  # NEW resource (see PREP)
      *) addr=""; echo "# UNMAPPED disk (review): $d" ;;
    esac
    [ -n "$addr" ] && echo "safe_import 'google_compute_disk.${addr}' 'projects/${PROJECT_ID}/zones/${ZONE}/disks/${d}'"
  done
note "PREP: config has phantom 'prod_mongodb_db' (no live disk of that name)."
note "Replace it with a 'prod_mongodb_primary' resource (name=mongodb-primary,"
note "50GB pd-ssd, prevent_destroy, ignore_changes=[labels,snapshot]) before import,"
note "mirroring the dev mongo-primary change."
echo

# -----------------------------------------------------------------------------
# 10. Cloud Armor security policies (map live -> config address by key suffix)
# -----------------------------------------------------------------------------
echo 'echo "--- google_compute_security_policy ---"'
gc compute security-policies list --format='value(name)' 2>/dev/null \
| while read -r p; do
    [ -z "$p" ] && continue
    matched=""
    for addr in admin bff datalandsbyen harvesters nginx_controller publishers registration search services sparql validator; do
      key="${addr//_/-}"
      case "$p" in *"$key") matched="$addr"; break;; esac
    done
    if [ -n "$matched" ]; then
      echo "safe_import 'google_compute_security_policy.${matched}' 'projects/${PROJECT_ID}/global/securityPolicies/${p}'"
    else
      echo "# UNMAPPED security policy (review): $p"
    fi
  done
echo

# -----------------------------------------------------------------------------
# 11. Disk snapshot resource policy
# -----------------------------------------------------------------------------
echo 'echo "--- google_compute_resource_policy ---"'
gc compute resource-policies list --format='value(name,region.basename())' 2>/dev/null \
| while IFS=$'\t' read -r name rgn; do
    [ -z "$name" ] && continue
    echo "safe_import 'google_compute_resource_policy.disk_backup_policy' 'projects/${PROJECT_ID}/regions/${rgn}/resourcePolicies/${name}'"
  done
echo

# -----------------------------------------------------------------------------
# 12. GKE cluster + node pools (import cluster BEFORE k8s resources)
# -----------------------------------------------------------------------------
echo 'echo "--- google_container_cluster / node pools ---"'
gc container clusters list --format='value(name,location)' 2>/dev/null \
| while IFS=$'\t' read -r cl loc; do
    [ -z "$cl" ] && continue
    echo "safe_import 'google_container_cluster.main' 'projects/${PROJECT_ID}/locations/${loc}/clusters/${cl}'"
    gc container node-pools list --cluster="$cl" --location="$loc" --format='value(name)' 2>/dev/null \
    | while read -r np; do
        [ -z "$np" ] && continue
        echo "safe_import 'google_container_node_pool.pools[\"${np}\"]' 'projects/${PROJECT_ID}/locations/${loc}/clusters/${cl}/nodePools/${np}'"
      done
  done
echo

# -----------------------------------------------------------------------------
# 13. Kubernetes resources (REQUIRE cluster credentials + kube provider)
#     These cannot be imported until the cluster is reachable:
#       gcloud container clusters get-credentials <cluster> --zone <zone>
#     Namespace + SA names live in the secret tfvars / cluster; emit guarded
#     templates rather than guess. Fill in actual names after creds are set.
# -----------------------------------------------------------------------------
cat <<'K8S'
echo "--- kubernetes_namespace / kubernetes_service_account ---"
# Requires: gcloud container clusters get-credentials digdir-fdk-prod --zone europe-north1-a --project digdir-fdk-prod
# kubernetes_namespace import id        = "<namespace>"
# kubernetes_service_account import id  = "<namespace>/<name>"
# Discover live names with:  kubectl get ns ; kubectl get sa -A
# Example (uncomment + adjust):
# safe_import 'kubernetes_namespace.prod' '<namespace>'
# safe_import 'kubernetes_service_account.monitoring_cloud_sql_sa' '<ns>/<sa>'
# safe_import 'kubernetes_service_account.workload_identity_service_accounts["<ns>-<sa>"]' '<ns>/<sa>'
K8S
echo
echo 'echo "=== import generation complete ==="'