#!/usr/bin/env bash
# AUTO-GENERATED by generate-imports.sh against live digdir-fdk-prod.
# Review carefully before running. Run from terraform/prod after:
#   terraform init -backend-config="bucket=digdir-fdk-prod-terraform-state"
#   (terraform.tfvars.secret-manager present)
set -uo pipefail

PROJECT_ID="digdir-fdk-prod"
REGION="europe-north1"
ZONE="europe-north1-a"

# Idempotent import: skip if already in state; never abort the whole run.
safe_import() {
  local addr="$1" id="$2"
  if terraform state show "$addr" >/dev/null 2>&1; then
    echo "  ⏭️  already in state: $addr"
  else
    echo "  ⬇️  importing: $addr"
    terraform import -var-file=terraform.tfvars.secret-manager "$addr" "$id" \
      || echo "  ⚠️  FAILED: $addr"
  fi
}

echo "=== Terraform import: production ==="

echo "--- google_project_service ---"
# Parsed from api-services.tf (address + service string are literals).
safe_import 'google_project_service.compute' 'digdir-fdk-prod/compute.googleapis.com'
safe_import 'google_project_service.container' 'digdir-fdk-prod/container.googleapis.com'
safe_import 'google_project_service.iam' 'digdir-fdk-prod/iam.googleapis.com'
safe_import 'google_project_service.cloudresourcemanager' 'digdir-fdk-prod/cloudresourcemanager.googleapis.com'
safe_import 'google_project_service.sqladmin' 'digdir-fdk-prod/sqladmin.googleapis.com'
safe_import 'google_project_service.sql_component' 'digdir-fdk-prod/sql-component.googleapis.com'
safe_import 'google_project_service.storage_api' 'digdir-fdk-prod/storage-api.googleapis.com'
safe_import 'google_project_service.storage_component' 'digdir-fdk-prod/storage-component.googleapis.com'
safe_import 'google_project_service.artifactregistry' 'digdir-fdk-prod/artifactregistry.googleapis.com'
safe_import 'google_project_service.logging' 'digdir-fdk-prod/logging.googleapis.com'
safe_import 'google_project_service.monitoring' 'digdir-fdk-prod/monitoring.googleapis.com'
safe_import 'google_project_service.clouderrorreporting' 'digdir-fdk-prod/clouderrorreporting.googleapis.com'
safe_import 'google_project_service.cloudtrace' 'digdir-fdk-prod/cloudtrace.googleapis.com'
safe_import 'google_project_service.iamcredentials' 'digdir-fdk-prod/iamcredentials.googleapis.com'
safe_import 'google_project_service.secretmanager' 'digdir-fdk-prod/secretmanager.googleapis.com'
safe_import 'google_project_service.containersecurity' 'digdir-fdk-prod/containersecurity.googleapis.com'
safe_import 'google_project_service.gkeconnect' 'digdir-fdk-prod/gkeconnect.googleapis.com'
safe_import 'google_project_service.gkehub' 'digdir-fdk-prod/gkehub.googleapis.com'
safe_import 'google_project_service.containerfilesystem' 'digdir-fdk-prod/containerfilesystem.googleapis.com'
safe_import 'google_project_service.containerregistry' 'digdir-fdk-prod/containerregistry.googleapis.com'
safe_import 'google_project_service.dns' 'digdir-fdk-prod/dns.googleapis.com'
safe_import 'google_project_service.networkconnectivity' 'digdir-fdk-prod/networkconnectivity.googleapis.com'
safe_import 'google_project_service.servicemanagement' 'digdir-fdk-prod/servicemanagement.googleapis.com'
safe_import 'google_project_service.serviceusage' 'digdir-fdk-prod/serviceusage.googleapis.com'
safe_import 'google_project_service.cloudapis' 'digdir-fdk-prod/cloudapis.googleapis.com'
safe_import 'google_project_service.cloudbuild' 'digdir-fdk-prod/cloudbuild.googleapis.com'
safe_import 'google_project_service.cloudfunctions' 'digdir-fdk-prod/cloudfunctions.googleapis.com'
safe_import 'google_project_service.run' 'digdir-fdk-prod/run.googleapis.com'
safe_import 'google_project_service.certificatemanager' 'digdir-fdk-prod/certificatemanager.googleapis.com'
safe_import 'google_project_service.oslogin' 'digdir-fdk-prod/oslogin.googleapis.com'

echo "--- google_service_account ---"
safe_import 'google_service_account.vertex_sa' 'projects/digdir-fdk-prod/serviceAccounts/digdir-fdk-prod-vertex-sa@digdir-fdk-prod.iam.gserviceaccount.com'
safe_import 'google_service_account.error_sa' 'projects/digdir-fdk-prod/serviceAccounts/digdir-fdk-prod-error-sa@digdir-fdk-prod.iam.gserviceaccount.com'
safe_import 'google_service_account.kubernetes' 'projects/digdir-fdk-prod/serviceAccounts/digdir-fdk-prod-kubernetes-sa@digdir-fdk-prod.iam.gserviceaccount.com'
safe_import 'google_service_account.bucket_sa' 'projects/digdir-fdk-prod/serviceAccounts/digdir-fdk-prod-bucket-sa@digdir-fdk-prod.iam.gserviceaccount.com'
safe_import 'google_service_account.autodeploy_sa' 'projects/digdir-fdk-prod/serviceAccounts/digdir-fdk-prod-autodeploy@digdir-fdk-prod.iam.gserviceaccount.com'
safe_import 'google_service_account.cloudsql_sa' 'projects/digdir-fdk-prod/serviceAccounts/digdir-fdk-prod-cloudsql@digdir-fdk-prod.iam.gserviceaccount.com'
safe_import 'google_service_account.eso_reader_sa' 'projects/digdir-fdk-prod/serviceAccounts/digdir-fdk-prod-eso-reader-sa@digdir-fdk-prod.iam.gserviceaccount.com'
# NOT live (create-on-apply, do not import): terraform_sa, k8s_deploy_sa, cf_invoker_sa (whichever are absent above)

echo "--- google_project_iam_member ---"
# WARN: terraform_sa email not found live — cannot emit terraform_sa IAM bindings
# WARN: k8s_deploy_sa email not found live — cannot emit k8s_deploy_sa IAM binding

echo "--- google_service_account_iam_member (WIF) ---"

echo "--- workload identity federation ---"
safe_import 'google_iam_workload_identity_pool.github_actions' 'projects/digdir-fdk-prod/locations/global/workloadIdentityPools/github-actions'
safe_import 'google_iam_workload_identity_pool_provider.github' 'projects/digdir-fdk-prod/locations/global/workloadIdentityPools/github-actions/providers/github'

echo "--- google_compute_global_address ---"
safe_import 'google_compute_global_address.addresses["prod-v4"]' 'projects/digdir-fdk-prod/global/addresses/digdir-fdk-prod-prod-v4'
safe_import 'google_compute_global_address.addresses["prod-v6"]' 'projects/digdir-fdk-prod/global/addresses/digdir-fdk-prod-prod-v6'

echo "--- google_storage_bucket ---"
# skip bucket 'digdir-fdk-prod-terraform-state' (not Terraform-managed: state backend / archive)
# skip bucket 'fdk-archive' (not Terraform-managed: state backend / archive)
safe_import 'google_storage_bucket.thanos_long_term_metrics' 'thanos-long-term-metric-storage'

echo "--- google_sql_database_instance ---"
safe_import 'google_sql_database_instance.main' 'digdir-fdk-prod/digdir-fdk-prod'
# PREP: before importing, mirror dev SQL config (parameterize edition/
# data_cache/transaction_log + retune flags) so the post-import plan is clean.

echo "--- google_compute_disk ---"
# UNMAPPED disk (review): fdk-harvest-archive
safe_import 'google_compute_disk.prod_cms_service' 'projects/digdir-fdk-prod/zones/europe-north1-a/disks/fdk-prod-cms-service'
safe_import 'google_compute_disk.prod_community_service' 'projects/digdir-fdk-prod/zones/europe-north1-a/disks/fdk-prod-community-service'
safe_import 'google_compute_disk.prod_kafka_1' 'projects/digdir-fdk-prod/zones/europe-north1-a/disks/fdk-prod-kafka-1'
safe_import 'google_compute_disk.prod_kafka_2' 'projects/digdir-fdk-prod/zones/europe-north1-a/disks/fdk-prod-kafka-2'
safe_import 'google_compute_disk.prod_kafka_3' 'projects/digdir-fdk-prod/zones/europe-north1-a/disks/fdk-prod-kafka-3'
safe_import 'google_compute_disk.prod_rabbitmq' 'projects/digdir-fdk-prod/zones/europe-north1-a/disks/fdk-prod-rabbitmq'
safe_import 'google_compute_disk.prod_reports_store' 'projects/digdir-fdk-prod/zones/europe-north1-a/disks/fdk-prod-reports-store'
safe_import 'google_compute_disk.prod_sparql' 'projects/digdir-fdk-prod/zones/europe-north1-a/disks/fdk-prod-sparql'
safe_import 'google_compute_disk.prod_static_rdf_server' 'projects/digdir-fdk-prod/zones/europe-north1-a/disks/fdk-prod-static-rdf-server'
safe_import 'google_compute_disk.prod_zookeeper_1' 'projects/digdir-fdk-prod/zones/europe-north1-a/disks/fdk-prod-zookeeper-1'
# UNMAPPED disk (review): gke-digdir-fdk-prod-f0-pvc-aa4b69d3-2ab6-474d-8791-70e8641fd055
# UNMAPPED disk (review): gke-digdir-fdk-prod-f0-pvc-e4d214a1-3f60-4a5b-80f8-4b9fb270752c
# UNMAPPED disk (review): gke-digdir-fdk-prod-f0-pvc-f40869d4-c55b-4b75-80db-db8be47834e2
# UNMAPPED disk (review): gke-digdir-fdk-prod-pool-4-a99318d1-5cmd
# UNMAPPED disk (review): gke-digdir-fdk-prod-pool-4-a99318d1-upnu
# UNMAPPED disk (review): gke-digdir-fdk-prod-pool-5-3aaadd73-0518
# UNMAPPED disk (review): gke-digdir-fdk-prod-pool-5-3aaadd73-9irn
# UNMAPPED disk (review): gke-digdir-fdk-prod-pool-5-3aaadd73-dboi
# UNMAPPED disk (review): gke-digdir-fdk-prod-pool-5-3aaadd73-fvc9
# UNMAPPED disk (review): gke-digdir-fdk-prod-pool-5-3aaadd73-nsag
# UNMAPPED disk (review): gke-digdir-fdk-prod-pool-5-3aaadd73-q711
safe_import 'google_compute_disk.prod_mongodb_primary' 'projects/digdir-fdk-prod/zones/europe-north1-a/disks/mongodb-primary'
# UNMAPPED disk (review): prod-fdk-formattingstation
# UNMAPPED disk (review): pvc-040673a0-7ae9-44f9-8df6-0227f84e77ca
# UNMAPPED disk (review): pvc-18bcfa2e-a93e-4fe4-a677-093fa0f739db
# UNMAPPED disk (review): pvc-48856226-34cd-4ca0-8b92-afb696dcab5a
# UNMAPPED disk (review): pvc-5044d80c-369a-4bde-a7f7-92b1dc680a6d
# UNMAPPED disk (review): pvc-992ddeb9-1bbd-4c50-8dea-b91675caf7e0
# UNMAPPED disk (review): pvc-a799dee5-a62c-45b7-8ae3-cb82e5ac41dc
# UNMAPPED disk (review): pvc-f06bd569-6de4-4a1b-abe3-32d304f3f74e
# UNMAPPED disk (review): pvc-f2f98c9a-b779-4caa-b5a0-bccdd759ac21
# UNMAPPED disk (review): pvc-feec9d7e-af0a-44ce-ba32-641beccd9131
# PREP: config has phantom 'prod_mongodb_db' (no live disk of that name).
# Replace it with a 'prod_mongodb_primary' resource (name=mongodb-primary,
# 50GB pd-ssd, prevent_destroy, ignore_changes=[labels,snapshot]) before import,
# mirroring the dev mongo-primary change.

echo "--- google_compute_security_policy ---"
safe_import 'google_compute_security_policy.admin' 'projects/digdir-fdk-prod/global/securityPolicies/digdir-fdk-cloud-armor-policy-admin'
safe_import 'google_compute_security_policy.bff' 'projects/digdir-fdk-prod/global/securityPolicies/digdir-fdk-cloud-armor-policy-bff'
safe_import 'google_compute_security_policy.datalandsbyen' 'projects/digdir-fdk-prod/global/securityPolicies/digdir-fdk-cloud-armor-policy-datalandsbyen'
safe_import 'google_compute_security_policy.harvesters' 'projects/digdir-fdk-prod/global/securityPolicies/digdir-fdk-cloud-armor-policy-harvesters'
safe_import 'google_compute_security_policy.publishers' 'projects/digdir-fdk-prod/global/securityPolicies/digdir-fdk-cloud-armor-policy-publishers'
safe_import 'google_compute_security_policy.registration' 'projects/digdir-fdk-prod/global/securityPolicies/digdir-fdk-cloud-armor-policy-registration'
safe_import 'google_compute_security_policy.search' 'projects/digdir-fdk-prod/global/securityPolicies/digdir-fdk-cloud-armor-policy-search'
safe_import 'google_compute_security_policy.services' 'projects/digdir-fdk-prod/global/securityPolicies/digdir-fdk-cloud-armor-policy-services'
safe_import 'google_compute_security_policy.sparql' 'projects/digdir-fdk-prod/global/securityPolicies/digdir-fdk-cloud-armor-policy-sparql'
safe_import 'google_compute_security_policy.validator' 'projects/digdir-fdk-prod/global/securityPolicies/digdir-fdk-cloud-armor-policy-validator'
safe_import 'google_compute_security_policy.nginx_controller' 'projects/digdir-fdk-prod/global/securityPolicies/digdir-fdk-prod-cloud-armor-nginx-controller'

echo "--- google_compute_resource_policy ---"
safe_import 'google_compute_resource_policy.disk_backup_policy' 'projects/digdir-fdk-prod/regions/europe-north1/resourcePolicies/fdk-prod-snapshot-europe-30-days'

echo "--- google_container_cluster / node pools ---"
safe_import 'google_container_cluster.main' 'projects/digdir-fdk-prod/locations/europe-north1-a/clusters/digdir-fdk-prod'
safe_import 'google_container_node_pool.pools["pool-4"]' 'projects/digdir-fdk-prod/locations/europe-north1-a/clusters/digdir-fdk-prod/nodePools/pool-4'
safe_import 'google_container_node_pool.pools["pool-5"]' 'projects/digdir-fdk-prod/locations/europe-north1-a/clusters/digdir-fdk-prod/nodePools/pool-5'

echo "--- kubernetes_namespace / kubernetes_service_account ---"
# Requires: gcloud container clusters get-credentials digdir-fdk-prod --zone europe-north1-a --project digdir-fdk-prod
# kubernetes_namespace import id        = "<namespace>"
# kubernetes_service_account import id  = "<namespace>/<name>"
# Discover live names with:  kubectl get ns ; kubectl get sa -A
# Example (uncomment + adjust):
# safe_import 'kubernetes_namespace.prod' '<namespace>'
# safe_import 'kubernetes_service_account.monitoring_cloud_sql_sa' '<ns>/<sa>'
# safe_import 'kubernetes_service_account.workload_identity_service_accounts["<ns>-<sa>"]' '<ns>/<sa>'

echo "=== import generation complete ==="
