---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-harvester-server
  namespace: staging
data:
  server.dataset.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           datasets.staging.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        limit_req zone=harvester_limit burst=3 delay=1;
        proxy_pass http://fdk-dataset-harvester:8080;
      }

    }
  server.data-service.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           dataservices.staging.fellesdatakatalog.digdir.no data-services.staging.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-dataservice-harvester:8080;
      }
    }
  server.concept.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           concepts.staging.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-concept-harvester:8080;
      }
    }
  server.information-model.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           informationmodels.staging.fellesdatakatalog.digdir.no information-models.staging.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-informationmodel-harvester:8080;
      }
    }
  server.event.conf: |  
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           events.staging.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-event-harvester:8080;
      }
    }
  server.service.conf: |  
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           services.staging.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-public-service-harvester:8080;
      }
    }  
