apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/nginx-harvester
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: staging
    target:
      kind: Deployment
      name: nginx-harvester
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: staging
    target:
      kind: ConfigMap
      name: nginx-harvester
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: staging
    target:
      kind: Service
      name: nginx-harvester
  - path: config-map.yaml
