---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/gitea
patches:
  - target:
      kind: HelmRelease
      name: gitea
    patch: |-
      - op: replace
        path: /metadata/name
        value: gitea-demo
patchesStrategicMerge:
  - helm-release-gitea.yaml
