---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nginx-controller
  namespace: prod
spec:
  healthCheck:
    requestPath: /healthz
  customRequestHeaders:
    # GKE adds the header 'X-Forwarded-Port: 443'. Nginx then forwards the
    # header instead of itself adding the header with value 80.
    headers:
      - X-Forwarded-Port:443
