---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: flux-system
spec:
  values:
    ingress:
      hosts:
        - host: kibana.dev.fellesdatakatalog.digdir.no
          paths:
            - path: /
