---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backstage
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      version: 1.4.x
      chart: backstage
      sourceRef:
        kind: HelmRepository
        name: backstage
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values: {}
