---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-monitoring-server
  namespace: monitoring
data:
  server.karma.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           karma.fellesdatakatalog.digdir.no;
      limit_req zone=monitoring_limit burst=15 delay=5;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://karma:8080;
      }
    }
  server.alertmanager.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           alertmanager.fellesdatakatalog.digdir.no;
      limit_req zone=monitoring_limit burst=15 delay=5;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://monitoring-kube-prometheus-alertmanager:9093;
      }
    }
  server.prometheus.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           prometheus.fellesdatakatalog.digdir.no;
      limit_req zone=monitoring_limit burst=15 delay=5;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://monitoring-kube-prometheus-prometheus:9090;
      }
    }
  server.grafana.conf: |  
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           grafana.fellesdatakatalog.digdir.no;
      limit_req zone=monitoring_limit burst=15 delay=5;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://monitoring-kube-prometheus-stack-grafana:8080;
      }
    }
  server.thanos.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           thanos.fellesdatakatalog.digdir.no;
      limit_req zone=monitoring_limit burst=15 delay=5;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://monitoring-thanos-query-frontend:9090;
      }
    }
  server.thanos-store.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           thanos-store.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=15 delay=5;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://monitoring-thanos-storagegateway:9090;
      }
    }
