---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-harvester-server
  namespace: demo
data:
  server.dataset.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           datasets.demo.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location / {
        deny all;
        return 410;
      }
    }
  server.data-service.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           dataservices.demo.fellesdatakatalog.digdir.no data-services.demo.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location / {
        deny all;
        return 410;
      }
    }
  server.concept.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           concepts.demo.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location / {
        deny all;
        return 410;
      }
    }
  server.information-model.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           informationmodels.demo.fellesdatakatalog.digdir.no information-models.demo.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location / {
        deny all;
        return 410;
      }
    }
  server.event.conf: |  
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           events.demo.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location / {
        deny all;
        return 410;
      }
    }
  server.service.conf: |  
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           services.demo.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location / {
        deny all;
        return 410;
      }
    }  
