---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dataset-catalog-frontend
  namespace: demo
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: dataset-catalog-frontend
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dataset-catalog-frontend-demo
