---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-client-credentials
  namespace: demo
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-client-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: keycloak-client-credentials-demo
