---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo
  namespace: demo
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: mongo
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mongo-demo
