---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sso
  namespace: demo
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: sso
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: sso-demo
