---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: access-request-api
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: access-request-api
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: access-request-api-staging
