---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-elasticsearch
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: catalog-elasticsearch
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: catalog-elasticsearch-staging
