---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: common
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: common
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: common-staging
