---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-service-catalog-frontend
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: data-service-catalog-frontend
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: data-service-catalog-frontend-staging
