---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dev-commonurl
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: dev-commonurl
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dev-commonurl-staging
