---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fdk-community-config
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: fdk-community-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: fdk-community-config-staging
