---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fdk-statistics-service
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: fdk-statistics-service
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: fdk-statistics-service-staging
