---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fdk-altinnproxy-staging-digdir-altinn-key
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: fdk-altinnproxy-staging-digdir-altinn-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: fdk-altinnproxy-staging-digdir-altinn-key-staging
