---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-admin
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: keycloak-admin-staging
