---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: mongodb
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mongodb-staging
