---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: postgres-staging
