---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terms-and-conditions
  namespace: staging
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: terms-and-conditions
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: terms-and-conditions-staging
