---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: behandlingsoversikt
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: behandlingsoversikt
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: behandlingsoversikt-prod
