---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-history-service
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: catalog-history-service
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: catalog-history-service-prod
