---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: commonurl
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: commonurl
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: commonurl-prod
