---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dataset-catalog
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: dataset-catalog
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dataset-catalog-prod
