---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-user-catalog-view-api
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: es-user-catalog-view-api
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: es-user-catalog-view-api-prod
