---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-user-fdk-reports-bff
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: es-user-fdk-reports-bff
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: es-user-fdk-reports-bff-prod
