---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fdk-sparql-service
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: fdk-sparql-service
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: fdk-sparql-service-prod
