---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fdk-altinnproxy-prod-digdir-altinn-key
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: fdk-altinnproxy-prod-digdir-altinn-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: fdk-altinnproxy-prod-digdir-altinn-key-prod
