---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: kafka-prod
