---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rdf-prettifier
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: rdf-prettifier
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: rdf-prettifier-prod
