---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: service-catalog-frontend
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: service-catalog-frontend
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: service-catalog-frontend-prod
