---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-monitoring-config.yaml
  - flux-monitoring-repo.yaml
  - kube-prometheus-stack.yaml
  - kube-prometheus-kafka-exporter.yaml
  - namespace.yaml
  - prometheus-community.yaml
