---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
  namespace: flux-system
spec:
  values:
    query:
      ingress:
        hostname: thanos-query.dev.fellesdatakatalog.digdir.no
    queryFrontend:
      ingress:
        hostname: thanos.dev.fellesdatakatalog.digdir.no
    storegateway:
      ingress:
        hostname: thanos-store.dev.fellesdatakatalog.digdir.no
    compactor:
      ingress:
        # enabled: true
        hostname: thanos-compactor.dev.fellesdatakatalog.digdir.no
