---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  values:
    alertmanager:
      ingress:
        hosts:
          - alertmanager.dev.fellesdatakatalog.digdir.no
    grafana:
      ingress:
        hosts:
          - grafana.dev.fellesdatakatalog.digdir.no
    prometheus:
      ingress:
        hosts:
          - prometheus.dev.fellesdatakatalog.digdir.no
