---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: catalog-mongodb
  namespace: flux-system
spec:
  interval: 120m
  url: oci://registry-1.docker.io/bitnamicharts/mongodb