---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 5m
  strategy:
    type: Recreate
  chart:
    spec:
      version: 9.x
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: gitea
      targetPath: gitea.admin.password
      valuesKey: password
  values:
    gitea:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      config:
        log:
          LEVEL: Warn
    ingress:
      enabled: false
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: ingress-basic-auth
        nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    resources:
      requests:
        cpu: 2000m
        memory: 800Mi
      limits:
        cpu: 3000m
        memory: 1200Mi
