---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb-demo
  namespace: flux-system
spec:
  targetNamespace: demo
  values:
    namespaceOverride: demo
  valuesFrom:
    - kind: Secret
      name: mongodb-demo
      targetPath: auth.rootPassword
      valuesKey: ROOT_PASSWORD
    - kind: Secret
      name: mongodb-demo
      targetPath: auth.replicaSetKey
      valuesKey: REPLICASET_KEY
