---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  targetNamespace: demo
  values:
    namespaceOverride: demo
    configuration: |-
      systemLog:
        quiet: true
