---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-demo-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  gcePersistentDisk:
    pdName: mongodb-demo-primary
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-demo-mongodb-demo-0
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: ""
  volumeName: mongodb-demo-pv
