---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-exporter
    creationPolicy: Owner
  data:
    - secretKey: DATA_SOURCE_NAME
      remoteRef:
        key: postgres-exporter
        property: connection_string