---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: flux-system
spec:
  targetNamespace: staging
  values:
    postgresql-ha:
      enabled: false
    redis-cluster:
      enabled: true
    gitea:
      config:
        database:
          DB_TYPE: postgres
    persistence:
      mount: true
      create: false
      claimName: data-staging-gitea-staging-0
  valuesFrom:
    # List is overwritten, not merged with base. Must therefore configure password here.
    - kind: Secret
      name: gitea-staging
      targetPath: gitea.admin.password
      valuesKey: ADMIN_PASSWORD
    - kind: Secret
      name: gitea-staging
      targetPath: gitea.config.database.HOST
      valuesKey: POSTGRES_HOST
    - kind: Secret
      name: gitea-staging
      targetPath: gitea.config.database.USER
      valuesKey: POSTGRES_USERNAME
    - kind: Secret
      name: gitea-staging
      targetPath: gitea.config.database.PASSWD
      valuesKey: POSTGRES_PASSWORD
    - kind: Secret
      name: gitea-staging
      targetPath: gitea.config.database.NAME
      valuesKey: POSTGRES_DB_NAME
