apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/gitea
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: gitea-staging
  target:
    kind: HelmRelease
    name: gitea
- path: helm-release-gitea.yaml
