---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: flux-system
spec:
  values:
    query:
      ingress:
        hostname: thanos-query.fellesdatakatalog.digdir.no
    queryFrontend:
      ingress:
        enabled: false
        hostname: thanos.fellesdatakatalog.digdir.no
    storegateway:
      ingress:
        enabled: false
        hostname: thanos-store.fellesdatakatalog.digdir.no
    compactor:
      ingress:
        hostname: thanos-compactor.fellesdatakatalog.digdir.no
