---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  values:
    alertmanager:
      ingress:
        enabled: false
        hosts:
          - alertmanager.fellesdatakatalog.digdir.no
    grafana:
      ingress:
        enabled: false
        hosts:
          - grafana.fellesdatakatalog.digdir.no
    prometheus:
      ingress:
        enabled: false
        hosts:
          - prometheus.fellesdatakatalog.digdir.no
