---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
  namespace: flux-system
spec:
  values:
    query:
      ingress:
        # enabled: true
        hostname: thanos-query.fellesdatakatalog.digdir.no
    queryFrontend:
      ingress:
        hostname: thanos.fellesdatakatalog.digdir.no
    storegateway:
      ingress:
        hostname: thanos-store.fellesdatakatalog.digdir.no
    compactor:
      ingress:
        # enabled: true
        hostname: thanos-compactor.fellesdatakatalog.digdir.no
