---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/monitoring
patchesStrategicMerge:
  - helm-release-kafka-exporter-values.yaml
  - helm-release-prometheus-values.yaml
  - helm-release-thanos-values.yaml
