---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-catalog-server
  namespace: demo
data:
  server.dataset.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           dataset-catalog.demo.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://dataset-catalog:8080;
      }
    }
  server.data-service.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           dataservice-catalog.demo.fellesdatakatalog.digdir.no data-service-catalog.demo.fellesdatakatalog.digdir.no;
      proxy_connect_timeout       600;
      proxy_send_timeout          600;
      proxy_read_timeout          600;
      send_timeout                600;
    
      client_max_body_size 50M;  
      gzip on;
      gzip_http_version  1.1;
      gzip_comp_level    5;
      gzip_min_length    256;
      gzip_proxied       any;
      gzip_vary          on;
      gzip_types
        application/atom+xml
        application/javascript
        application/json
        application/rss+xml
        application/x-font-ttf
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/opentype
        image/svg+xml
        image/x-icon
        text/css
        text/plain
        text/x-component
        text/turtle;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location /catalogs {
        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Allow-Origin' '*';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, PATCH, DELETE, OPTIONS';
          #
          # Custom headers and headers various browsers *should* be OK with but aren't
          #
          add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
          #
          # Tell client that this pre-flight info is valid for 20 days
          #
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain; charset=utf-8';
          add_header 'Content-Length' 0;
          return 204;
        }
        proxy_pass http://dataservice-catalog:8080;
      }
    
      location / {
        proxy_pass http://dataservice-catalog-gui:8080;
      }
    }
  server.concept.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           concept-catalog.demo.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://concept-catalog:8080;
      }
    }
  server.service.conf: |  
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           service-catalog.demo.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://service-catalog:8080;
      }
    }
  server.terms.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           terms.demo.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://terms-and-conditions:8080;
      }
    }
  server.catalog-admin.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           catalog-admin-service.demo.fellesdatakatalog.digdir.no catalog-admin.api.demo.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://catalog-admin-service:8080;
      }
    }
  server.catalog-comments.conf: |    
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           catalog-comments.demo.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://catalog-comments-service:8080;
      }
    }
  server.catalog-history.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           catalog-history.demo.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://catalog-history-service:8080;
      }
    }
  server.catalog-portal.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           catalog-portal.demo.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ /prometheus/?$ {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://catalog-portal:8080;
      }
    }