apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-internal-tls
  namespace: staging
spec:
  issuerRef:
    name: letsencrypt-dev # Use dev environment issuer
  dnsNames:
    - keycloak.staging.fellesdatakatalog.digdir.no
