---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base/nginx-resource-identificators
  - ingress.yaml
configMapGenerator:
  - name: nginx-resource-identificators-server
    files:
      - server.information-models.conf
      - server.catalogs.conf
