---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nginx-controller
  namespace: nginx
spec:
  healthCheck:
    requestPath: /healthz
  customRequestHeaders:
    headers:
      - X-Forwarded-Port:443
