---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nginx
  chart:
    spec:
      version: 2.x
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
      config:
        proxy-set-headers: nginx/custom-headers
        hide-headers: X-Forwarded-Proto
      service:
        type: NodePort
        annotations:
          cloud.google.com/backend-config: '{"default": "nginx-controller"}'
