---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nginx
  chart:
    spec:
      version: 4.x
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      allowSnippetAnnotations: true
      annotations:
        # Scrape nginx controller pod for metrics.
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
      config:
        # Forward all 'X-Forwarded-*' headers, added by GKE loadbalancer.
        use-forwarded-headers: "true"
        # Append the remote address to the X-Forwarded-For header instead of replacing it.
        compute-full-forwarded-for: "true"
      service:
        type: NodePort
        annotations:
          # See backend-config.yaml.
          cloud.google.com/backend-config: '{"default": "nginx-controller"}'
