---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-controller
  namespace: nginx
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: nginx-controller
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: nginx-nginx-controller
                port:
                  number: 80
            path: /
            pathType: Prefix
