---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: catalog-elasticsearch
  namespace: staging
spec:
  version: 8.x
  nodeSets:
    - name: master
      count: 2
      config:
        node.roles: ["master"]
    - name: data
      count: 4
      config:
        node.roles: ["data", "ingest", "transform"]
      podTemplate:
        spec:
        initContainers:
        - name: increase-the-vm-max-map-count
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
#        - name: fix-rights
#          securityContext:
#            privileged: true
#            runAsUser: 0
#          command:
#            - /bin/chmod
#            - "777"
#            - /usr/share/elasticsearch/data
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: -Xms2G -Xmx2G
              - name: xpack.security.enabled
                value: "true"
              - name: cluster.name
                value: catalog-elasticsearch
              - name: ELASTIC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: catalog-elasticsearch
                    key: ELASTIC_PASSWORD
            resources:
              requests:
                memory: 6Gi
                cpu: 500m
              limits:
                memory: 10Gi
                cpu: 2
            volumeMounts:
              - name: data
                mountPath: /usr/share/elasticsearch/data
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: catalog-elasticsearch
  values:
    namespaceOverride: staging
