---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-staging-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: elasticsearch-staging-data
    fsType: ext4
  claimRef:
    namespace: staging
    name: elasticsearch-data-elasticsearch-es-data-0