---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matomo
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: matomo
  chart:
    spec:
      version: 0.2.x
      chart: matomo
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values: {}
