---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: digdir-fdk-dev
      auth:
        workloadIdentity:
          clusterName: digdir-fdk-dev
          clusterLocation: europe-north1-a
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
