---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: flux-system
spec:
  targetNamespace: staging
  values:
    ingress:
      hosts:
        - host: gitea.staging.fellesdatakatalog.digdir.no
          paths:
            - path: /
              pathType: Prefix
    postgres:
      enabled: false
    gitea:
      config:
        database:
          DB_TYPE: postgres
  valuesFrom:
    - kind: Secret
      name: gitea-staging
      targetPath: gitea.config.database.HOST
      valuesKey: POSTGRES_HOST
    - kind: Secret
      name: gitea-staging
      targetPath: gitea.config.database.USER
      valuesKey: POSTGRES_USERNAME
    - kind: Secret
      name: gitea-staging
      targetPath: gitea.config.database.PASSWD
      valuesKey: POSTGRES_PASSWORD
    - kind: Secret
      name: gitea-staging
      targetPath: gitea.config.database.NAME
      valuesKey: POSTGRES_DB_NAME
