---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-harvester-server
  namespace: prod
data:
  server.dataset.conf: |
    server {
      listen                8080;
      server_name           datasets.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/prometheus {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-dataset-harvester:8080;
      }
    }
  server.data-service.conf: |
    server {
      listen                8080;
      server_name           dataservices.fellesdatakatalog.digdir.no data-services.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/prometheus {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-dataservice-harvester:8080;
      }
    }
  server.concept.conf: |
    server {
      listen                8080;
      server_name           concepts.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/prometheus {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-concept-harvester:8080;
      }
    }
  server.information-model.conf: |
    server {
      listen                8080;
      server_name           informationmodels.fellesdatakatalog.digdir.no information-models.fellesdatakatalog.digdir.no;
       limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/prometheus {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-informationmodel-harvester:8080;
      }
    }
  server.event.conf: |  
    server {
      listen                8080;
      server_name           events.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/prometheus {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-event-harvester:8080;
      }
    }
  server.service.conf: |  
    server {
      listen                8080;
      server_name           services.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/prometheus {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-public-service-harvester:8080;
      }
    }  
