---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-harvester-server
  namespace: prod
data:
  server.dataset.conf: |
    server {
      listen                8080;
      server_name           datasets.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-dataset-harvester:8080;
      }
    }
  server.data-service.conf: |
    server {
      listen                8080;
      server_name           dataservices.fellesdatakatalog.digdir.no data-services.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-dataservice-harvester:8080;
      }
    }
  server.concept.conf: |
    server {
      listen                8080;
      server_name           concepts.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-concept-harvester:8080;
      }
    }
  server.information-model.conf: |
    server {
      listen                8080;
      server_name           informationmodels.fellesdatakatalog.digdir.no information-models.fellesdatakatalog.digdir.no;
       limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-informationmodel-harvester:8080;
      }
    }
  server.event.conf: |  
    server {
      listen                8080;
      server_name           events.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-event-harvester:8080;
      }
    }
  server.service.conf: |  
    server {
      listen                8080;
      server_name           services.fellesdatakatalog.digdir.no;
      limit_req zone=harvester_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://fdk-public-service-harvester:8080;
      }
    }  
  server.terms.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           terms.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://terms-and-conditions:8080;
      }
    }
  server.catalog-admin.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           catalog-admin-service.fellesdatakatalog.digdir.no catalog-admin.api.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://catalog-admin-service:8080;
      }
    }
  server.catalog-comments.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           catalog-comments.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://catalog-comments-service:8080;
      }
    }
  server.catalog-history.conf: |
    server {
      # Use the mapped $client_ip
      set_real_ip_from 10.0.0.0/8;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      listen                8080;
      server_name           catalog-history.fellesdatakatalog.digdir.no;
      limit_req zone=catalog_limit burst=3 delay=1;
    
      location ~ ^/(ping|ready|prometheus) {
        deny all;
        return 404;
      }
    
      location / {
        proxy_pass http://catalog-history-service:8080;
      }
    }
