---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: logging
  chart:
    spec:
      version: 7.x
      chart: kibana
      sourceRef:
        kind: HelmRepository
        name: elastic
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    kibanaConfig:
      kibana.yml: |
        elasticsearch.hosts: http://elasticsearch-master:9200
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: ingress-basic-auth
        nginx.ingress.kubernetes.io/auth-realm: Authentication Required
