---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: logging
  chart:
    spec:
      version: 0.x
      chart: fluentd
      sourceRef:
        kind: HelmRepository
        name: fluent
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    fileConfigs:
      01_sources.conf: |-
        <source>
          @type tail
          @id in_tail_container_logs
          @label @KUBERNETES
          path /var/log/containers/*.log
          pos_file /var/log/fluentd-containers.log.pos
          tag kubernetes.*
          read_from_head true
          <parse>
            @type multi_format
            <pattern>
              format json
              time_key time
              time_type string
              time_format "%Y-%m-%dT%H:%M:%S.%NZ"
              keep_time_key true
            </pattern>
            <pattern>
              format regexp
              expression /^(?<time>.+) (?<stream>stdout|stderr)( (.))? (?<log>.*)$/
              time_format '%Y-%m-%dT%H:%M:%S.%NZ'
              keep_time_key true
            </pattern>
          </parse>
          emit_unmatched_lines true
        </source>
      02_filters.conf: |-
        <label @KUBERNETES>
          <filter kubernetes.**>
            @type parser
            key_name log
            reserve_data true
            remove_key_name_field false
            hash_value_field json
            emit_invalid_record_to_error false
            <parse>
              @type json
            </parse>
          </filter>

          <match kubernetes.var.log.containers.fluentd**>
            @type relabel
            @label @FLUENT_LOG
          </match>

          <match kubernetes.var.log.containers.**_kube-system_**>
            @type null
            @id ignore_kube_system_logs
          </match>

          <filter kubernetes.**>
            @type kubernetes_metadata
            @id filter_kube_metadata
            skip_labels false
            skip_container_metadata false
            skip_namespace_metadata true
            skip_master_url true
          </filter>

          <match **>
            @type relabel
            @label @DISPATCH
          </match>
        </label>
