---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release-elasticsearch.yaml
  - helm-release-fluentd.yaml
  - helm-release-kibana.yaml
  - helm-repo-elastic.yaml
  - helm-repo-fluent.yaml
  - namespace.yaml
