apiVersion: keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  hostname:
    hostname: keycloak.demo.fellesdatakatalog.digdir.no
    admin: keycloak-admin.demo.fellesdatakatalog.digdir.no
  instances: 2
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 2Gi  
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dev
  additionalOptions:
    - name: KC_DB_HOST
      secret:
        name: postgres-demo
        key: HOST
    - name: KC_DB_PORT
      secret:
        name: postgres-demo
        key: PORT
    - name: KC_DB_DATABASE
      secret:
        name: keycloak
        key: POSTGRESQL_DB
    - name: KC_DB_USERNAME
      secret:
        name: keycloak
        key: POSTGRESQL_USER
    - name: KC_DB_PASSWORD
      secret:
        name: keycloak
        key: POSTGRESQL_PASSWORD
