apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-keycloak
resources:
  - ../../base/keycloak
patches:
  - target:
      kind: Keycloak
      name: keycloak
    patch: |-
      - op: add
        path: /spec/hostname
        value:
          hostname: keycloak.staging.fellesdatakatalog.digdir.no
          admin: keycloak-admin.staging.fellesdatakatalog.digdir.no
      - op: replace
        path: /spec/instances
        value: 1
      - op: add
        path: /spec/resources
        value:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
      - op: replace
        path: /spec/ingress/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-dev
      - op: add
        path: /spec/additionalOptions/-
        value:
          name: KC_DB_HOST
          secret:
            name: postgres-staging
            key: HOST
      - op: add
        path: /spec/additionalOptions/-
        value:
          name: KC_DB_PORT
          secret:
            name: postgres-staging
            key: PORT
      - op: add
        path: /spec/additionalOptions/-
        value:
          name: KC_DB_DATABASE
          secret:
            name: keycloak
            key: POSTGRESQL_DB
      - op: add
        path: /spec/additionalOptions/-
        value:
          name: KC_DB_USERNAME
          secret:
            name: keycloak
            key: POSTGRESQL_USER
      - op: add
        path: /spec/additionalOptions/-
        value:
          name: KC_DB_PASSWORD
          secret:
            name: keycloak
            key: POSTGRESQL_PASSWORD
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: keycloak-internal-tls
