---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-resource-identificators
  namespace: demo
spec:
  ingressClassName: nginx
  rules:
    - host: information-models.demo.fellesdatakatalog.digdir.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-resource-identificators
                port:
                  number: 8080
    - host: catalogs.demo.fellesdatakatalog.digdir.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-resource-identificators
                port:
                  number: 8080
