server {
  # Use the mapped $client_ip
  set_real_ip_from 10.0.0.0/8;
  real_ip_header X-Forwarded-For;
  real_ip_recursive on;
  listen                8080;
  server_name           information-models.demo.fellesdatakatalog.digdir.no;
  limit_req zone=identificator_limit burst=15 delay=5;

  if ($request_method !~ ^(GET|HEAD)$) {
    return 405;
  }

  # /<id> -> the information model graph in catalog-backend
  location ~ ^/[^/]+$ {
    rewrite ^/([^/]+)$ /graphs/information-models/$1 break;
    proxy_pass http://catalog-backend:8080;
  }

  location / {
    return 404;
  }
}
