---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backstage
  namespace: flux-system
spec:
  targetNamespace: staging
  values:
    namespaceOverride: staging
    backstage:
      extraEnvVars:
        - name: APP_CONFIG_backend_database_client
          value: pg
      extraEnvVarsSecrets:
        - backstage

