apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/backstage
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: backstage
  target:
    kind: HelmRelease
    name: backstage
- path: helm-release-backstage.yaml
