---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: ingress-nginx
  chart:
    spec:
      version: 2.x
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      service:
        external:
          enabled: false
        internal:
          enabled: true
