---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repo.yaml
  - ingress-nginx.yaml
  - namespace.yaml
  - backend-config.yaml
  - frontend-config.yaml
  - ingress.yaml
