apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/nginx-misc
- config-map.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: prod
    target:
      kind: Deployment
      name: nginx-misc
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: prod
    target:
      kind: ConfigMap
      name: nginx-misc
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: prod
    target:
      kind: Service
      name: nginx-misc
