---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-harvester
  labels:
    app: nginx-harvester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-harvester
  template:
    metadata:
      labels:
        app: nginx-harvester
    spec:
      containers:
        - name: nginx-harvester
          image: nginx:alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: config
              subPath: nginx.conf
            - mountPath: /etc/nginx/conf.d/server.dataset.conf
              name: config-server
              subPath: server.dataset.conf
            - mountPath: /etc/nginx/conf.d/server.data-service.conf
              name: config-server
              subPath: server.data-service.conf
            - mountPath: /etc/nginx/conf.d/server.concept.conf
              name: config-server
              subPath: server.concept.conf
            - mountPath: /etc/nginx/conf.d/server.information-model.conf
              name: config-server
              subPath: server.information-model.conf
      volumes:
        - name: "config"
          configMap:
            name: "nginx-harvester"
        - name: "config-server"
          configMap:
            name: "nginx-harvester-server"
