---
apiVersion: v1
kind: Service
metadata:
  name: nginx-harvester
spec:
  selector:
    app: nginx-harvester
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
type: NodePort
