---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-map.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: nginx-misc-error-pages
    files:
      - favicon.ico
      - community-maintenance.html