---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: prod
spec:
  version: 8.10.4
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
    - name: master
      count: 2
      config:
        node.roles: ["master"]
      podTemplate:
        spec:
          initContainers:
            - name: increase-the-vm-max-map-count
              securityContext:
                privileged: true
                runAsUser: 0
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              env:
                - name: xpack.security.enabled
                  value: "true"
                - name: cluster.name
                  value: elasticsearch
                - name: ELASTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: elasticsearch-es
                      key: ELASTIC_PASSWORD
              resources:
                requests:
                  memory: 2Gi
                  cpu: 100m
                limits:
                  memory: 4Gi
                  cpu: 300m
    - name: data
      count: 4
      config:
        node.roles: ["data", "ingest", "transform"]
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: standard
      podTemplate:
        spec:
          initContainers:
            - name: increase-the-vm-max-map-count
              securityContext:
                privileged: true
                runAsUser: 0
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: -Xms2G -Xmx2G
              - name: xpack.security.enabled
                value: "true"
              - name: cluster.name
                value: elasticsearch
              - name: ELASTIC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: elasticsearch-es
                    key: ELASTIC_PASSWORD
            resources:
              requests:
                memory: 6Gi
                cpu: 500m
              limits:
                memory: 10Gi
                cpu: 2
            volumeMounts:
              - name: data
                mountPath: /usr/share/elasticsearch/data
