---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: catalog-mongodb-staging
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 10s
  path: ./apps/dev/catalog-mongodb-staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
