---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-demo
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 10s
  path: ./apps/dev/keycloak-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: keycloak-operator
