---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitea-demo.yaml
  - gitea-staging.yaml
  - catalog-mongodb-staging.yaml
  - backstage-staging.yaml
  - catalog-elasticsearch-staging.yaml
