---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-harvester-demo
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 10s
  path: ./apps/dev/nginx-harvester-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
