---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-catalog-demo
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 10s
  path: ./apps/dev/nginx-catalog-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    cmd:
      - kubectl
      - rollout
      - restart
      - deployment/nginx-catalog
      - --namespace=demo
