---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: catalog-mongodb
  namespace: flux-system
spec:
  targetNamespace: staging
  values:
    namespaceOverride: staging
  valuesFrom:
    - kind: Secret
      name: catalog-mongodb-staging
      targetPath: auth.rootPassword
      valuesKey: ROOT_PASSWORD
    - kind: Secret
      name: catalog-mongodb-staging
      targetPath: auth.replicaSetKey
      valuesKey: REPLICASET_KEY
