apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/catalog-mongodb
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: catalog-mongodb
  target:
    kind: HelmRelease
    name: catalog-mongodb
- path: helm-release-mongodb.yaml
