---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/catalog-mongodb
patches:
  - target:
      kind: HelmRelease
      name: catalog-mongodb
patchesStrategicMerge:
  - helm-release-mongodb.yaml
