---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: matomo
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 10s
  path: ./infrastructure/base/matomo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: nginx
