---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/keycloak-operator
  - rbac-prod.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: prod
    target:
      kind: Deployment
      name: keycloak-operator
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: prod
    target:
      kind: NetworkPolicy
      name: keycloak-operator-network-policy
  - patch: |-
      - op: replace
        path: /spec/selector/matchLabels/app
        value: keycloak-operator-prod
      - op: replace
        path: /spec/template/metadata/labels/app
        value: keycloak-operator-prod
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: keycloak-operator-prod
    target:
      kind: Deployment
      name: keycloak-operator
