resource "google_storage_bucket" "thanos_long_term_metrics" {
  force_destroy = false

  labels = {
    managed-by-cnrm = "true"
  }

  location                 = upper(var.region)
  name                     = var.storage_buckets.thanos_bucket_name
  project                  = var.project_id
  public_access_prevention = "enforced"

  soft_delete_policy {
    retention_duration_seconds = 604800
  }

  storage_class               = "STANDARD"
  uniform_bucket_level_access = true
}

resource "google_service_account" "thanos_sa" {
  account_id   = var.service_accounts.thanos
  description  = "Service account for Thanos access to the long-term metrics bucket"
  display_name = "${var.project_id}-thanos-sa"
  project      = var.project_id
}

# Scoped to the metrics bucket only, not project-wide storage access, matching
# the es_snapshot_sa pattern. Thanos reaches the bucket through Workload
# Identity, so no service account key is involved.
resource "google_storage_bucket_iam_member" "thanos_object_admin" {
  bucket = google_storage_bucket.thanos_long_term_metrics.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${google_service_account.thanos_sa.email}"
}

# The three workloads that touch the bucket. Query and query-frontend read
# through the storegateway and the sidecars, so they need no bucket access.
# These names are generated by the Helm charts from the release names already
# declared in infrastructure/base/monitoring, so they are not secret and are
# kept here rather than in tfvars.
locals {
  thanos_bucket_k8s_service_accounts = [
    "monitoring-thanos-compactor",
    "monitoring-thanos-storegateway",
    "monitoring-kube-prometheus-prometheus",
  ]
}

resource "google_service_account_iam_member" "thanos_workload_identity" {
  for_each = toset(local.thanos_bucket_k8s_service_accounts)

  service_account_id = google_service_account.thanos_sa.name
  role               = "roles/iam.workloadIdentityUser"
  member             = "serviceAccount:${var.project_id}.svc.id.goog[${var.monitoring_namespace}/${each.value}]"
}

# No service_account key: Thanos falls back to ADC via Workload Identity.
# External Secrets delivers this into the namespace.
resource "google_secret_manager_secret" "thanos_objstore" {
  secret_id = "thanos-objstore"
  project   = var.project_id

  labels = {
    namespace = var.monitoring_namespace
  }

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "thanos_objstore" {
  secret = google_secret_manager_secret.thanos_objstore.id

  secret_data = jsonencode({
    "objstore.yml" = yamlencode({
      type = "GCS"
      config = {
        bucket = var.storage_buckets.thanos_bucket_name
      }
    })
  })
}

# The Helm charts own these service accounts, so only the annotation is managed
# here rather than the objects. Set from Terraform so the account address is not
# committed to this repo, which is public.
resource "kubernetes_annotations" "thanos_workload_identity" {
  for_each = toset(local.thanos_bucket_k8s_service_accounts)

  api_version = "v1"
  kind        = "ServiceAccount"
  force       = true

  metadata {
    name      = each.value
    namespace = var.monitoring_namespace
  }

  annotations = {
    "iam.gke.io/gcp-service-account" = google_service_account.thanos_sa.email
  }
}
