---
# ServiceAccount for Keycloak operator in demo namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-operator-demo
  namespace: demo
---
# ClusterRoleBinding for Keycloak operator in demo namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-operator-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keycloak-operator
subjects:
  - kind: ServiceAccount
    name: keycloak-operator-demo
    namespace: demo
