---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      version: 16.x
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: mongodb
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
        ephemeral-storage: 5Gi
      limits:
        memory: 1Gi
        ephemeral-storage: 10Gi
    architecture: replicaset
    nameOverride: mongodb
    replicaCount: 3
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      resourcesPreset: none
    persistence:
      resourcePolicy: keep
      size: 10Gi
    arbiter:
      enabled: false
