---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-oci
  namespace: flux-system
spec:
  type: "oci"
  interval: 120m
  url: oci://registry-1.docker.io/bitnamicharts
