---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-postgres-exporter
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: monitoring
  chart:
    spec:
      version: 7.x
      chart: prometheus-postgres-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    config:
      # Connection string from secret (keeps all connection details private)
      datasourceSecret:
        name: postgres-exporter
        key: DATA_SOURCE_NAME

      # Enable default metrics
      disableDefaultMetrics: false
      disableSettingsMetrics: false
      autoDiscoverDatabases: true

      # Custom queries for enhanced monitoring
      queries: |-
        # Connection statistics
        pg_stat_activity_connections:
          query: |
            SELECT
              COUNT(*) as total,
              COUNT(*) FILTER (WHERE state = 'active') as active,
              COUNT(*) FILTER (WHERE state = 'idle') as idle,
              COUNT(*) FILTER (WHERE state = 'idle in transaction') as idle_in_transaction,
              COUNT(*) FILTER (WHERE wait_event_type IS NOT NULL) as waiting
            FROM pg_stat_activity
            WHERE datname IS NOT NULL
          master: true
          metrics:
            - total:
                usage: "GAUGE"
                description: "Total number of connections"
            - active:
                usage: "GAUGE"
                description: "Number of active connections"
            - idle:
                usage: "GAUGE"
                description: "Number of idle connections"
            - idle_in_transaction:
                usage: "GAUGE"
                description: "Number of connections idle in transaction"
            - waiting:
                usage: "GAUGE"
                description: "Number of connections waiting"

        # Max connections setting
        pg_settings_max_connections:
          query: "SELECT setting::float as max_connections FROM pg_settings WHERE name = 'max_connections'"
          master: true
          metrics:
            - max_connections:
                usage: "GAUGE"
                description: "Maximum number of concurrent connections"

        # Database statistics
        pg_stat_database:
          query: |
            SELECT
              datname,
              numbackends,
              xact_commit,
              xact_rollback,
              blks_read,
              blks_hit,
              tup_returned,
              tup_fetched,
              tup_inserted,
              tup_updated,
              tup_deleted
            FROM pg_stat_database
            WHERE datname IS NOT NULL
          master: true
          metrics:
            - datname:
                usage: "LABEL"
                description: "Name of the database"
            - numbackends:
                usage: "GAUGE"
                description: "Number of backends currently connected to this database"
            - xact_commit:
                usage: "COUNTER"
                description: "Number of transactions committed"
            - xact_rollback:
                usage: "COUNTER"
                description: "Number of transactions rolled back"
            - blks_read:
                usage: "COUNTER"
                description: "Number of disk blocks read"
            - blks_hit:
                usage: "COUNTER"
                description: "Number of buffer cache hits"
            - tup_returned:
                usage: "COUNTER"
                description: "Number of rows returned"
            - tup_fetched:
                usage: "COUNTER"
                description: "Number of rows fetched"
            - tup_inserted:
                usage: "COUNTER"
                description: "Number of rows inserted"
            - tup_updated:
                usage: "COUNTER"
                description: "Number of rows updated"
            - tup_deleted:
                usage: "COUNTER"
                description: "Number of rows deleted"

    serviceMonitor:
      enabled: true
      interval: 30s

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      capabilities:
        drop:
          - ALL
