---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: monitoring
  chart:
    spec:
      version: 7.x
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    serviceMonitor:
      enabled: true
      targets:
        - name: datajegeren
          url: https://datafabrikken.norge.no/finn-data/datajegeren
