---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: monitoring
  chart:
    spec:
      version: 15.x
      chart: thanos
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    existingObjstoreSecret: thanos-objstore
    query:
      extraFlags:
        - --query.auto-downsampling
      dnsDiscovery:
        enabled: true
        sidecarsService: monitoring-kube-prometheus-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: false
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: ingress-basic-auth
          nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    queryFrontend:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: ingress-basic-auth
          nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    storegateway:
      enabled: true
      persistence:
        size: 24Gi
      resources:
        requests:
          memory: 2500Mi
          cpu: 150m
      networkPolicy:
        enabled: false
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: ingress-basic-auth
          nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    compactor:
      enabled: true
      persistence:
        size: 24Gi
      ingress:
        enabled: false
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: ingress-basic-auth
          nginx.ingress.kubernetes.io/auth-realm: Authentication Required
      retentionResolutionRaw: 14d
      retentionResolution5m: 30d
      retentionResolution1h: 10y
