---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: monitoring
  chart:
    spec:
      version: 7.x
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    serviceMonitor:
      enabled: true
      targets:
        - name: fdk
          url: https://data.norge.no/
        - name: datalandsbyen
          url: https://datalandsbyen.norge.no/
        - name: datafabrikken
          url: https://datafabrikken.norge.no/
        - name: datajegeren
          url: https://datafabrikken.norge.no/finn-data/datajegeren
#
# TODO: TEST Probe
#
# kind: Probe
# apiVersion: monitoring.coreos.com/v1
# metadata:
#   name: probes
#   namespace: monitoring
# spec:
#   interval: 60s
#   module: http_2xx
#   prober:
#     url: monitoring-blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
#   targets:
#     staticConfig:
#       static:
#       - https://google.com/
