---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karma
  namespace: monitoring
  labels:
    app: karma
spec:
  selector:
    matchLabels:
      app: karma
  template:
    metadata:
      labels:
        app: karma
    spec:
      containers:
        - name: karma
          image: ghcr.io/prymitive/karma:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /karma.yaml
              subPath: karma.yaml
      volumes:
        - name: config
          configMap:
            name: karma-config
            optional: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: karma-config
  namespace: monitoring
data:
  karma.yaml: |
    alertmanager:
      servers:
        - name: alertmanager
          uri: http://monitoring-kube-prometheus-alertmanager.monitoring:9093
    filters:
      default:
        - alertname!=Watchdog
        - alertname!=InfoInhibitor
---
apiVersion: v1
kind: Service
metadata:
  name: karma
  namespace: monitoring
spec:
  selector:
    app: karma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karma
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: ingress-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
spec:
  ingressClassName: nginx
  rules: []
