apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-internal-tls
  namespace: prod
spec:
  issuerRef:
    name: letsencrypt-prod # Use production environment issuer
  dnsNames:
    - auth.fellesdatakatalog.digdir.no
