apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: prod
spec:
  hostname:
    hostname: https://keycloak.fellesdatakatalog.digdir.no
    admin: https://keycloak.fellesdatakatalog.digdir.no
  instances: 3
  update:
    strategy: Explicit
    revision: "1"
  http:
    httpEnabled: false
    httpsPort: 8443
    tlsSecret: keycloak-internal-tls
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: "4"
      memory: 8Gi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/session-cookie-name: "KEYCLOAK_ROUTE"
      nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      nginx.ingress.kubernetes.io/server-snippet: |
        location /metrics {
          deny all;
          return 404;
        }
        location /realms/master/protocol/openid-connect/userinfo {
          deny all;
          return 404;
        }
      cert-manager.io/cluster-issuer: letsencrypt-prod
    className: nginx
  readinessProbe:
    periodSeconds: 20
    failureThreshold: 5
  livenessProbe:
    periodSeconds: 20
    failureThreshold: 5
  features:
    enabled:
      - admin-fine-grained-authz
      - ciba
      - client-auth-federated
      - dynamic-scopes
      - organization
      - recovery-codes
      - scripts
  additionalOptions:
    - name: KC_DB
      value: "postgres"
    - name: KC_CACHE
      value: "ispn"
    - name: KC_CACHE_CONFIG_FILE
      value: "cache-ispn.xml"
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KC_METRICS_ENABLED
      value: "true"
    - name: KC_LOG_LEVEL
      value: "INFO"
    - name: KC_DB_HOST
      secret:
        name: postgres
        key: HOST
    - name: KC_DB_PORT
      secret:
        name: postgres
        key: PORT
    - name: KC_DB_DATABASE
      secret:
        name: keycloak
        key: POSTGRESQL_DB
    - name: KC_DB_USERNAME
      secret:
        name: keycloak
        key: POSTGRESQL_USER
    - name: KC_DB_PASSWORD
      secret:
        name: keycloak
        key: POSTGRESQL_PASSWORD
  env:
    - name: USER_API_KEY
      secret:
        name: common
        key: SSO_API_KEY
    - name: FDK_CLIENT_SECRET
      secret:
        name: sso
        key: FDK_CLIENT_SECRET
    - name: FDK_PORTAL_BASE_URI
      secret:
        name: sso
        key: FDK_PORTAL_BASE_URI
    - name: FDK_COMMUNITY_BASE_URI
      secret:
        name: commonurl
        key: FDK_COMMUNITY_BASE_URI
    - name: ADMIN_GUI_BASE_URI
      secret:
        name: commonurl
        key: ADMIN_GUI_BASE_URI
    - name: FDK_REGISTRATION_BASE_URI
      secret:
        name: commonurl
        key: FDK_REGISTRATION_BASE_URI
