apiVersion: keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  hostname:
    hostname: keycloak.fellesdatakatalog.digdir.no
    admin: keycloak-admin.fellesdatakatalog.digdir.no
  instances: 3
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 4
      memory: 8Gi
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  additionalOptions:
    - name: KC_DB_HOST
      secret:
        name: postgres-prod
        key: HOST
    - name: KC_DB_PORT
      secret:
        name: postgres-prod
        key: PORT
    - name: KC_DB_DATABASE
      secret:
        name: keycloak
        key: POSTGRESQL_DB
    - name: KC_DB_USERNAME
      secret:
        name: keycloak
        key: POSTGRESQL_USER
    - name: KC_DB_PASSWORD
      secret:
        name: keycloak
        key: POSTGRESQL_PASSWORD
