apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base/keycloak
patches:
  - path: keycloak-patch.yaml
    target:
      kind: Keycloak
      name: keycloak
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: keycloak-internal-tls
